/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package supportapp;

/*
 *  ComputingButtonPage.java
 *  18/04/2013
 * @author Paul Cuffe 11378541
 *
 */

public class ComputingButtonPage extends javax.swing.JFrame {

    /**
     * Creates new form ComputingButtonPage
     */
    public ComputingButtonPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        tutorial1JButton = new javax.swing.JButton();
        tutorial2JButton = new javax.swing.JButton();
        tutorial3JButton = new javax.swing.JButton();
        tutorial4JButton = new javax.swing.JButton();
        buttonpageJLabel = new javax.swing.JLabel();
        homeJButton = new javax.swing.JButton();
        mathsJButton = new javax.swing.JButton();
        disabilityJButton = new javax.swing.JButton();
        learningJButton = new javax.swing.JButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tutorial1JButton.setText("Tutorial 1");
        tutorial1JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tutorial1JButtonActionPerformed(evt);
            }
        });
        tutorial1JButton.setBounds(20, 180, 100, 40);
        jLayeredPane1.add(tutorial1JButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        tutorial2JButton.setText("Tutorial 2");
        tutorial2JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tutorial2JButtonActionPerformed(evt);
            }
        });
        tutorial2JButton.setBounds(200, 180, 100, 40);
        jLayeredPane1.add(tutorial2JButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        tutorial3JButton.setText("Tutorial 3");
        tutorial3JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tutorial3JButtonActionPerformed(evt);
            }
        });
        tutorial3JButton.setBounds(20, 260, 100, 40);
        jLayeredPane1.add(tutorial3JButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        tutorial4JButton.setText("Tutorial 4");
        tutorial4JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tutorial4JButtonActionPerformed(evt);
            }
        });
        tutorial4JButton.setBounds(200, 260, 100, 40);
        jLayeredPane1.add(tutorial4JButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        buttonpageJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/supportapp/Computing Button Page.jpg"))); // NOI18N
        buttonpageJLabel.setBounds(0, 0, 330, 490);
        jLayeredPane1.add(buttonpageJLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        homeJButton.setText("Home");
        homeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeJButtonActionPerformed(evt);
            }
        });
        homeJButton.setBounds(20, 380, 90, 30);
        jLayeredPane1.add(homeJButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        mathsJButton.setText("Maths");
        mathsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mathsJButtonActionPerformed(evt);
            }
        });
        mathsJButton.setBounds(20, 423, 90, 30);
        jLayeredPane1.add(mathsJButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        disabilityJButton.setText("Disability");
        disabilityJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disabilityJButtonActionPerformed(evt);
            }
        });
        disabilityJButton.setBounds(210, 380, 90, 30);
        jLayeredPane1.add(disabilityJButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        learningJButton.setText("Learning");
        learningJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                learningJButtonActionPerformed(evt);
            }
        });
        learningJButton.setBounds(210, 423, 90, 30);
        jLayeredPane1.add(learningJButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jInternalFrame1.setBounds(150, 180, 22, 53);
        jLayeredPane1.add(jInternalFrame1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tutorial1JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tutorial1JButtonActionPerformed
        dispose();
        Tutorial1 DGUI = new Tutorial1();
        DGUI.setVisible(true);
    }//GEN-LAST:event_tutorial1JButtonActionPerformed

    private void homeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeJButtonActionPerformed
        dispose();
        HomeScreen DGUI = new HomeScreen();
        DGUI.setVisible(true);
    }//GEN-LAST:event_homeJButtonActionPerformed

    private void mathsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mathsJButtonActionPerformed
        dispose();
        MathsSupport DGUI = new MathsSupport();
        DGUI.setVisible(true);
    }//GEN-LAST:event_mathsJButtonActionPerformed

    private void disabilityJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disabilityJButtonActionPerformed
        dispose();
        DisabilitySupport DGUI = new DisabilitySupport();
        DGUI.setVisible(true);
    }//GEN-LAST:event_disabilityJButtonActionPerformed

    private void learningJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_learningJButtonActionPerformed
        dispose();
        LearningSupport DGUI = new LearningSupport();
        DGUI.setVisible(true);
    }//GEN-LAST:event_learningJButtonActionPerformed

    private void tutorial2JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tutorial2JButtonActionPerformed
        dispose();
        Tutorial2 DGUI = new Tutorial2();
        DGUI.setVisible(true);
    }//GEN-LAST:event_tutorial2JButtonActionPerformed

    private void tutorial3JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tutorial3JButtonActionPerformed
        dispose();
        Tutorial3 DGUI = new Tutorial3();
        DGUI.setVisible(true);
    }//GEN-LAST:event_tutorial3JButtonActionPerformed

    private void tutorial4JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tutorial4JButtonActionPerformed
        dispose();
        Tutorial4 DGUI = new Tutorial4();
        DGUI.setVisible(true);
    }//GEN-LAST:event_tutorial4JButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComputingButtonPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComputingButtonPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComputingButtonPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComputingButtonPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ComputingButtonPage().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel buttonpageJLabel;
    private javax.swing.JButton disabilityJButton;
    private javax.swing.JButton homeJButton;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JButton learningJButton;
    private javax.swing.JButton mathsJButton;
    private javax.swing.JButton tutorial1JButton;
    private javax.swing.JButton tutorial2JButton;
    private javax.swing.JButton tutorial3JButton;
    private javax.swing.JButton tutorial4JButton;
    // End of variables declaration//GEN-END:variables
}
