/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package supportapp;

/*
 *  HomeScreen.java
 *  18/04/2013
 * @author Joseph Tierney 12329666
 *
 */

public class HomeScreen extends javax.swing.JFrame {

    /**
     * Creates new form HomeScreen
     */
    public HomeScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homescreenJP = new javax.swing.JLayeredPane();
        backgroundJL = new javax.swing.JLabel();
        disabilityJB = new javax.swing.JButton();
        mathsJB = new javax.swing.JButton();
        computingJB = new javax.swing.JButton();
        learningJB = new javax.swing.JButton();
        cmpunkJB = new javax.swing.JButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backgroundJL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/supportapp/App-Home-Design.jpg"))); // NOI18N
        backgroundJL.setBounds(0, 0, 320, 490);
        homescreenJP.add(backgroundJL, javax.swing.JLayeredPane.DEFAULT_LAYER);

        disabilityJB.setText("Disability");
        disabilityJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disabilityJBActionPerformed(evt);
            }
        });
        disabilityJB.setBounds(23, 383, 80, 30);
        homescreenJP.add(disabilityJB, javax.swing.JLayeredPane.DEFAULT_LAYER);

        mathsJB.setText("Maths");
        mathsJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mathsJBActionPerformed(evt);
            }
        });
        mathsJB.setBounds(213, 383, 80, 30);
        homescreenJP.add(mathsJB, javax.swing.JLayeredPane.DEFAULT_LAYER);

        computingJB.setText("Compute");
        computingJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                computingJBActionPerformed(evt);
            }
        });
        computingJB.setBounds(23, 430, 80, 23);
        homescreenJP.add(computingJB, javax.swing.JLayeredPane.DEFAULT_LAYER);

        learningJB.setText("Learning");
        learningJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                learningJBActionPerformed(evt);
            }
        });
        learningJB.setBounds(213, 430, 80, 23);
        homescreenJP.add(learningJB, javax.swing.JLayeredPane.DEFAULT_LAYER);

        cmpunkJB.setText("CM Punk");
        cmpunkJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmpunkJBActionPerformed(evt);
            }
        });
        cmpunkJB.setBounds(133, 100, 130, 40);
        homescreenJP.add(cmpunkJB, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        jInternalFrame1.setBounds(180, 210, 22, 37);
        homescreenJP.add(jInternalFrame1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homescreenJP, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homescreenJP, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void learningJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_learningJBActionPerformed
        dispose();
        LearningSupport DGUI = new LearningSupport();
        DGUI.setVisible(true);
    }//GEN-LAST:event_learningJBActionPerformed

    private void disabilityJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disabilityJBActionPerformed
        dispose();
        DisabilitySupport DGUI = new DisabilitySupport();
        DGUI.setVisible(true);
    }//GEN-LAST:event_disabilityJBActionPerformed

    private void mathsJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mathsJBActionPerformed
        dispose();
        MathsSupport DGUI = new MathsSupport();
        DGUI.setVisible(true);
    }//GEN-LAST:event_mathsJBActionPerformed

    private void computingJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_computingJBActionPerformed
        dispose();
        ComputingSupport DGUI = new ComputingSupport();
        DGUI.setVisible(true);
    }//GEN-LAST:event_computingJBActionPerformed

    private void cmpunkJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmpunkJBActionPerformed
        dispose();
        CMPunkGUI DGUI = new CMPunkGUI();
        DGUI.setVisible(true);
    }//GEN-LAST:event_cmpunkJBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new HomeScreen().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundJL;
    private javax.swing.JButton cmpunkJB;
    private javax.swing.JButton computingJB;
    private javax.swing.JButton disabilityJB;
    private javax.swing.JLayeredPane homescreenJP;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JButton learningJB;
    private javax.swing.JButton mathsJB;
    // End of variables declaration//GEN-END:variables
}
