/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package supportapp;

/*
 *  LearningStyles.java
 *  18/04/2013
 * @author Joseph Tierney 12329666
 * @reference https://moodle.ncirl.ie/course/view.php?id=878/ArraysOfObjectsTriggerApplication.java
 */

public class LearningStyles extends javax.swing.JFrame {

    private String feedbackText;
    private LearningStyles qArray[];
    //declare count variable to keep track of how many objects are in array
    private int count;

    /**
     * Creates new form LearningStyles
     */
    public LearningStyles() {
        initComponents();
        feedbackText = new String();
       LearningStyles[] a = new LearningStyles[0];
        //initialise count to 0
        LearningStyles a1;
        LearningStyles a2;
        LearningStyles a3;
        LearningStyles a4;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane2 = new javax.swing.JLayeredPane();
        feedbackTf = new javax.swing.JTextField();
        submitJB = new javax.swing.JButton();
        homeJB = new javax.swing.JButton();
        LearningStylesGUI = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        feedbackTf.setBounds(10, 370, 300, 30);
        jLayeredPane2.add(feedbackTf, javax.swing.JLayeredPane.DEFAULT_LAYER);

        submitJB.setText("Submit");
        submitJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJBActionPerformed(evt);
            }
        });
        submitJB.setBounds(110, 420, 100, 30);
        jLayeredPane2.add(submitJB, javax.swing.JLayeredPane.DEFAULT_LAYER);

        homeJB.setText("Home");
        homeJB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeJBActionPerformed(evt);
            }
        });
        homeJB.setBounds(140, 70, 80, 23);
        jLayeredPane2.add(homeJB, javax.swing.JLayeredPane.DEFAULT_LAYER);

        LearningStylesGUI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/supportapp/Learning Styles.jpg"))); // NOI18N
        LearningStylesGUI.setBounds(0, 0, 320, 480);
        jLayeredPane2.add(LearningStylesGUI, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeJBActionPerformed
        dispose();
        HomeScreen DGUI = new HomeScreen();
        DGUI.setVisible(true);
    }//GEN-LAST:event_homeJBActionPerformed

    private void submitJBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJBActionPerformed
        // Get text from TextFields
        feedbackText = feedbackTf.getText();
        
        //create a new Question object
        
        
        //add contents of textfields to q
        
        
        //add q to array of Question objects
        
        //increase count to show that another object has been added to the array
        
        dispose();
        LearningStyles DGUI = new LearningStyles();
        DGUI.setVisible(true);
    }//GEN-LAST:event_submitJBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LearningStyles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LearningStyles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LearningStyles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LearningStyles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new LearningStyles().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LearningStylesGUI;
    private javax.swing.JTextField feedbackTf;
    private javax.swing.JButton homeJB;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JButton submitJB;
    // End of variables declaration//GEN-END:variables

    private void setFeedbackText(String feedbackText) {
    }
}
