/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package supportapp;

/*
 *  LearningSupport.java
 *  18/04/2013
 * @author Joseph Tierney 12329666
 *
 */

public class LearningSupport extends javax.swing.JFrame {

    /**
     * Creates new form LearningSupport
     */
    public LearningSupport() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LearningSupportGUI = new javax.swing.JLayeredPane();
        resoucreJButton = new javax.swing.JButton();
        LearningGUI = new javax.swing.JLabel();
        homeJButton = new javax.swing.JButton();
        disabilityJButton = new javax.swing.JButton();
        mathsJButton = new javax.swing.JButton();
        comptuingJButton = new javax.swing.JButton();
        learningJButton = new javax.swing.JButton();
        notetakingJButton = new javax.swing.JButton();
        revisiontechJButton = new javax.swing.JButton();
        studyJButton = new javax.swing.JButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        resoucreJButton.setText("Resources");
        resoucreJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resoucreJButtonActionPerformed(evt);
            }
        });
        resoucreJButton.setBounds(130, 70, 100, 30);
        LearningSupportGUI.add(resoucreJButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        LearningGUI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/supportapp/Learning-Support-Home-Page.jpg"))); // NOI18N
        LearningGUI.setBounds(0, 0, 330, 480);
        LearningSupportGUI.add(LearningGUI, javax.swing.JLayeredPane.DEFAULT_LAYER);

        homeJButton.setText("Home");
        homeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeJButtonActionPerformed(evt);
            }
        });
        homeJButton.setBounds(23, 380, 80, 23);
        LearningSupportGUI.add(homeJButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        disabilityJButton.setText("Disability");
        disabilityJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disabilityJButtonActionPerformed(evt);
            }
        });
        disabilityJButton.setBounds(213, 380, 80, 23);
        LearningSupportGUI.add(disabilityJButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        mathsJButton.setText("Maths");
        mathsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mathsJButtonActionPerformed(evt);
            }
        });
        mathsJButton.setBounds(23, 420, 80, 30);
        LearningSupportGUI.add(mathsJButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        comptuingJButton.setText("Computing");
        comptuingJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comptuingJButtonActionPerformed(evt);
            }
        });
        comptuingJButton.setBounds(213, 423, 80, 23);
        LearningSupportGUI.add(comptuingJButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        learningJButton.setText("Learning");
        learningJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                learningJButtonActionPerformed(evt);
            }
        });
        learningJButton.setBounds(180, 220, 90, 20);
        LearningSupportGUI.add(learningJButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        notetakingJButton.setText("Notes");
        notetakingJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notetakingJButtonActionPerformed(evt);
            }
        });
        notetakingJButton.setBounds(37, 240, 70, 20);
        LearningSupportGUI.add(notetakingJButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        revisiontechJButton.setText("Revision");
        revisiontechJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revisiontechJButtonActionPerformed(evt);
            }
        });
        revisiontechJButton.setBounds(110, 240, 120, 20);
        LearningSupportGUI.add(revisiontechJButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        studyJButton.setText("Study");
        studyJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studyJButtonActionPerformed(evt);
            }
        });
        studyJButton.setBounds(270, 220, 50, 23);
        LearningSupportGUI.add(studyJButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 104, Short.MAX_VALUE)
        );

        jInternalFrame1.setBounds(160, 200, 22, 137);
        LearningSupportGUI.add(jInternalFrame1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LearningSupportGUI, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LearningSupportGUI, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeJButtonActionPerformed
        dispose();
        HomeScreen DGUI = new HomeScreen();
        DGUI.setVisible(true);
    }//GEN-LAST:event_homeJButtonActionPerformed

    private void disabilityJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disabilityJButtonActionPerformed
        dispose();
        DisabilitySupport DGUI = new DisabilitySupport();
        DGUI.setVisible(true);
    }//GEN-LAST:event_disabilityJButtonActionPerformed

    private void mathsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mathsJButtonActionPerformed
        dispose();
        MathsSupport DGUI = new MathsSupport();
        DGUI.setVisible(true);
    }//GEN-LAST:event_mathsJButtonActionPerformed

    private void comptuingJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comptuingJButtonActionPerformed
        dispose();
        ComputingSupport DGUI = new ComputingSupport();
        DGUI.setVisible(true);
    }//GEN-LAST:event_comptuingJButtonActionPerformed

    private void learningJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_learningJButtonActionPerformed
        dispose();
        LearningStyles DGUI = new LearningStyles();
        DGUI.setVisible(true);
    }//GEN-LAST:event_learningJButtonActionPerformed

    private void notetakingJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notetakingJButtonActionPerformed
        dispose();
        NoteTaking DGUI = new NoteTaking();
        DGUI.setVisible(true);     
    }//GEN-LAST:event_notetakingJButtonActionPerformed

private void revisiontechJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revisiontechJButtonActionPerformed
        dispose();
        RevisionTech DGUI = new RevisionTech();
        DGUI.setVisible(true);
   
}//GEN-LAST:event_revisiontechJButtonActionPerformed

private void studyJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studyJButtonActionPerformed
        dispose();
        StudySkills DGUI = new StudySkills();
        DGUI.setVisible(true);   
}//GEN-LAST:event_studyJButtonActionPerformed

    private void resoucreJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resoucreJButtonActionPerformed
        dispose();
        LearningButtonPage DGUI = new LearningButtonPage();
        DGUI.setVisible(true);
    }//GEN-LAST:event_resoucreJButtonActionPerformed
             
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LearningSupport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LearningSupport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LearningSupport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LearningSupport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new LearningSupport().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LearningGUI;
    private javax.swing.JLayeredPane LearningSupportGUI;
    private javax.swing.JButton comptuingJButton;
    private javax.swing.JButton disabilityJButton;
    private javax.swing.JButton homeJButton;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JButton learningJButton;
    private javax.swing.JButton mathsJButton;
    private javax.swing.JButton notetakingJButton;
    private javax.swing.JButton resoucreJButton;
    private javax.swing.JButton revisiontechJButton;
    private javax.swing.JButton studyJButton;
    // End of variables declaration//GEN-END:variables
}
