/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package supportapp;

/*
 *  MathsButtonPage.java
 *  18/04/2013
 * @author Kevin Fitzpatrick 12477932
 *
 */

public class MathsButtonPage extends javax.swing.JFrame {

    /**
     * Creates new form MathsButtonPage
     */
    public MathsButtonPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        workshopJButton = new javax.swing.JButton();
        calculatorJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        homeJButton = new javax.swing.JButton();
        disabilityJButton = new javax.swing.JButton();
        computingJButton = new javax.swing.JButton();
        learningJButton = new javax.swing.JButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        workshopJButton.setText("Workshop");
        workshopJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workshopJButtonActionPerformed(evt);
            }
        });
        workshopJButton.setBounds(10, 200, 130, 70);
        jLayeredPane1.add(workshopJButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        calculatorJButton.setText("Calculator");
        calculatorJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculatorJButtonActionPerformed(evt);
            }
        });
        calculatorJButton.setBounds(180, 200, 130, 70);
        jLayeredPane1.add(calculatorJButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/supportapp/Maths Button Page.jpg"))); // NOI18N
        jLabel1.setBounds(0, 0, 320, 480);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        homeJButton.setText("Home");
        homeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeJButtonActionPerformed(evt);
            }
        });
        homeJButton.setBounds(20, 380, 90, 30);
        jLayeredPane1.add(homeJButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        disabilityJButton.setText("Disability");
        disabilityJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disabilityJButtonActionPerformed(evt);
            }
        });
        disabilityJButton.setBounds(210, 380, 90, 23);
        jLayeredPane1.add(disabilityJButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        computingJButton.setText("Computing");
        computingJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                computingJButtonActionPerformed(evt);
            }
        });
        computingJButton.setBounds(20, 420, 90, 30);
        jLayeredPane1.add(computingJButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        learningJButton.setText("Learning");
        learningJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                learningJButtonActionPerformed(evt);
            }
        });
        learningJButton.setBounds(210, 420, 90, 30);
        jLayeredPane1.add(learningJButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        jInternalFrame1.setBounds(160, 60, 22, 37);
        jLayeredPane1.add(jInternalFrame1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeJButtonActionPerformed
        dispose();
        HomeScreen DGUI = new HomeScreen();
        DGUI.setVisible(true);
    }//GEN-LAST:event_homeJButtonActionPerformed

    private void disabilityJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disabilityJButtonActionPerformed
        dispose();
        DisabilitySupport DGUI = new DisabilitySupport();
        DGUI.setVisible(true);
    }//GEN-LAST:event_disabilityJButtonActionPerformed

    private void computingJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_computingJButtonActionPerformed
        dispose();
        ComputingSupport DGUI = new ComputingSupport();
        DGUI.setVisible(true);
    }//GEN-LAST:event_computingJButtonActionPerformed

    private void learningJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_learningJButtonActionPerformed
        dispose();
        LearningSupport DGUI = new LearningSupport();
        DGUI.setVisible(true);
    }//GEN-LAST:event_learningJButtonActionPerformed

    private void workshopJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workshopJButtonActionPerformed
        dispose();
        MathsWorkshop DGUI = new MathsWorkshop();
        DGUI.setVisible(true);
    }//GEN-LAST:event_workshopJButtonActionPerformed

    private void calculatorJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculatorJButtonActionPerformed
        dispose();
        MathsCalculator DGUI = new MathsCalculator();
        DGUI.setVisible(true);
    }//GEN-LAST:event_calculatorJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MathsButtonPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MathsButtonPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MathsButtonPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MathsButtonPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MathsButtonPage().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculatorJButton;
    private javax.swing.JButton computingJButton;
    private javax.swing.JButton disabilityJButton;
    private javax.swing.JButton homeJButton;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JButton learningJButton;
    private javax.swing.JButton workshopJButton;
    // End of variables declaration//GEN-END:variables
}
