/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package supportapp;

/*
 *  ComputingSupport.java
 *  18/04/2013
 * @author Paul Cuffe 11378541
 *
 */

public class ComputingSupport extends javax.swing.JFrame {

    /**
     * Creates new form ComputingSupport
     */
    public ComputingSupport() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ComputingSupportGUI = new javax.swing.JLayeredPane();
        resourcesJButton = new javax.swing.JButton();
        ComptuingGUI = new javax.swing.JLabel();
        homeJButton = new javax.swing.JButton();
        disabilityJButton = new javax.swing.JButton();
        mathsJButton = new javax.swing.JButton();
        learningJButton = new javax.swing.JButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        resourcesJButton.setText("Resources");
        resourcesJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resourcesJButtonActionPerformed(evt);
            }
        });
        resourcesJButton.setBounds(130, 80, 100, 30);
        ComputingSupportGUI.add(resourcesJButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        ComptuingGUI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/supportapp/Computing-Support-Home.jpg"))); // NOI18N
        ComptuingGUI.setBounds(0, 0, 330, 490);
        ComputingSupportGUI.add(ComptuingGUI, javax.swing.JLayeredPane.DEFAULT_LAYER);

        homeJButton.setText("Home");
        homeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeJButtonActionPerformed(evt);
            }
        });
        homeJButton.setBounds(20, 383, 90, 30);
        ComputingSupportGUI.add(homeJButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        disabilityJButton.setText("Disability");
        disabilityJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disabilityJButtonActionPerformed(evt);
            }
        });
        disabilityJButton.setBounds(213, 383, 80, 30);
        ComputingSupportGUI.add(disabilityJButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        mathsJButton.setText("Maths");
        mathsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mathsJButtonActionPerformed(evt);
            }
        });
        mathsJButton.setBounds(20, 430, 90, 23);
        ComputingSupportGUI.add(mathsJButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        learningJButton.setText("Learning");
        learningJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                learningJButtonActionPerformed(evt);
            }
        });
        learningJButton.setBounds(213, 430, 80, 23);
        ComputingSupportGUI.add(learningJButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 32, Short.MAX_VALUE)
        );

        jInternalFrame1.setBounds(160, 240, 22, 65);
        ComputingSupportGUI.add(jInternalFrame1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ComputingSupportGUI, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ComputingSupportGUI, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeJButtonActionPerformed
        dispose();
        HomeScreen DGUI = new HomeScreen();
        DGUI.setVisible(true);
    }//GEN-LAST:event_homeJButtonActionPerformed

    private void disabilityJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disabilityJButtonActionPerformed
        dispose();
        DisabilitySupport DGUI = new DisabilitySupport();
        DGUI.setVisible(true);
    }//GEN-LAST:event_disabilityJButtonActionPerformed

    private void mathsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mathsJButtonActionPerformed
        dispose();
        MathsSupport DGUI = new MathsSupport();
        DGUI.setVisible(true);
    }//GEN-LAST:event_mathsJButtonActionPerformed

    private void learningJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_learningJButtonActionPerformed
        dispose();
        LearningSupport DGUI = new LearningSupport();
        DGUI.setVisible(true);
    }//GEN-LAST:event_learningJButtonActionPerformed

    private void resourcesJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resourcesJButtonActionPerformed
        dispose();
        ComputingButtonPage DGUI = new ComputingButtonPage();
        DGUI.setVisible(true);
    }//GEN-LAST:event_resourcesJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComputingSupport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComputingSupport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComputingSupport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComputingSupport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ComputingSupport().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ComptuingGUI;
    private javax.swing.JLayeredPane ComputingSupportGUI;
    private javax.swing.JButton disabilityJButton;
    private javax.swing.JButton homeJButton;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JButton learningJButton;
    private javax.swing.JButton mathsJButton;
    private javax.swing.JButton resourcesJButton;
    // End of variables declaration//GEN-END:variables
}
