/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package supportapp;

/*
 *  LearningButtonPage.java
 *  18/04/2013
 * @author Joseph Tierney 12329666
 *
 */

public class LearningButtonPage extends javax.swing.JFrame {

    /**
     * Creates new form LearningButtonPage
     */
    public LearningButtonPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        studyskillsJButton = new javax.swing.JButton();
        learningstylesJButton = new javax.swing.JButton();
        revisionJButton = new javax.swing.JButton();
        noteJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        homeJButton = new javax.swing.JButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        studyskillsJButton.setText("Study Skills");
        studyskillsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studyskillsJButtonActionPerformed(evt);
            }
        });
        studyskillsJButton.setBounds(190, 180, 120, 40);
        jLayeredPane1.add(studyskillsJButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        learningstylesJButton.setText("Learning Styles");
        learningstylesJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                learningstylesJButtonActionPerformed(evt);
            }
        });
        learningstylesJButton.setBounds(10, 180, 130, 40);
        jLayeredPane1.add(learningstylesJButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        revisionJButton.setText("Revision Techniques");
        revisionJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                revisionJButtonActionPerformed(evt);
            }
        });
        revisionJButton.setBounds(10, 250, 130, 40);
        jLayeredPane1.add(revisionJButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        noteJButton.setText("Note Taking");
        noteJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noteJButtonActionPerformed(evt);
            }
        });
        noteJButton.setBounds(190, 250, 120, 40);
        jLayeredPane1.add(noteJButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/supportapp/Learning Button Page.jpg"))); // NOI18N
        jLabel1.setBounds(0, 0, 320, 490);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        homeJButton.setText("Home");
        homeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeJButtonActionPerformed(evt);
            }
        });
        homeJButton.setBounds(20, 380, 90, 30);
        jLayeredPane1.add(homeJButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        jInternalFrame1.setBounds(140, 390, 22, 37);
        jLayeredPane1.add(jInternalFrame1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studyskillsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studyskillsJButtonActionPerformed
        dispose();
        StudySkills DGUI = new StudySkills();
        DGUI.setVisible(true);
    }//GEN-LAST:event_studyskillsJButtonActionPerformed

    private void learningstylesJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_learningstylesJButtonActionPerformed
        dispose();
        LearningStyles DGUI = new LearningStyles();
        DGUI.setVisible(true);
    }//GEN-LAST:event_learningstylesJButtonActionPerformed

    private void revisionJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_revisionJButtonActionPerformed
        dispose();
        RevisionTech DGUI = new RevisionTech();
        DGUI.setVisible(true);
    }//GEN-LAST:event_revisionJButtonActionPerformed

    private void noteJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noteJButtonActionPerformed
        dispose();
        NoteTaking DGUI = new NoteTaking();
        DGUI.setVisible(true);
    }//GEN-LAST:event_noteJButtonActionPerformed

    private void homeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeJButtonActionPerformed
        dispose();
        HomeScreen DGUI = new HomeScreen();
        DGUI.setVisible(true);
    }//GEN-LAST:event_homeJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LearningButtonPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LearningButtonPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LearningButtonPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LearningButtonPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new LearningButtonPage().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton homeJButton;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JButton learningstylesJButton;
    private javax.swing.JButton noteJButton;
    private javax.swing.JButton revisionJButton;
    private javax.swing.JButton studyskillsJButton;
    // End of variables declaration//GEN-END:variables
}
