/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package supportapp;

/*
 *  MathsSupport.java
 *  18/04/2013
 * @author Kevin Fitzpatrick 12477932
 *
 */

public class MathsSupport extends javax.swing.JFrame {

    /**
     * Creates new form MathsSupport
     */
    public MathsSupport() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MathsSupportGUI = new javax.swing.JLayeredPane();
        resourcesJButton = new javax.swing.JButton();
        MathsGUI = new javax.swing.JLabel();
        homeJButton = new javax.swing.JButton();
        disabilityJButton = new javax.swing.JButton();
        computingJButton = new javax.swing.JButton();
        learningJButton = new javax.swing.JButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        resourcesJButton.setText("Resources");
        resourcesJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resourcesJButtonActionPerformed(evt);
            }
        });
        resourcesJButton.setBounds(130, 73, 100, 30);
        MathsSupportGUI.add(resourcesJButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        MathsGUI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/supportapp/Maths-Support-Home.jpg"))); // NOI18N
        MathsGUI.setBounds(0, 0, 330, 490);
        MathsSupportGUI.add(MathsGUI, javax.swing.JLayeredPane.DEFAULT_LAYER);

        homeJButton.setText("Home");
        homeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeJButtonActionPerformed(evt);
            }
        });
        homeJButton.setBounds(23, 380, 80, 30);
        MathsSupportGUI.add(homeJButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        disabilityJButton.setText("Disability");
        disabilityJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disabilityJButtonActionPerformed(evt);
            }
        });
        disabilityJButton.setBounds(213, 383, 80, 30);
        MathsSupportGUI.add(disabilityJButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        computingJButton.setText("Computing");
        computingJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                computingJButtonActionPerformed(evt);
            }
        });
        computingJButton.setBounds(23, 430, 80, 23);
        MathsSupportGUI.add(computingJButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        learningJButton.setText("Learning");
        learningJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                learningJButtonActionPerformed(evt);
            }
        });
        learningJButton.setBounds(220, 430, 73, 23);
        MathsSupportGUI.add(learningJButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jInternalFrame1.setBounds(170, 220, 22, 53);
        MathsSupportGUI.add(jInternalFrame1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MathsSupportGUI, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MathsSupportGUI, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeJButtonActionPerformed
        dispose();
        HomeScreen DGUI = new HomeScreen();
        DGUI.setVisible(true);
    }//GEN-LAST:event_homeJButtonActionPerformed

    private void disabilityJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disabilityJButtonActionPerformed
        dispose();
        DisabilitySupport DGUI = new DisabilitySupport();
        DGUI.setVisible(true);
    }//GEN-LAST:event_disabilityJButtonActionPerformed

    private void computingJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_computingJButtonActionPerformed
        dispose();
        ComputingSupport DGUI = new ComputingSupport();
        DGUI.setVisible(true);
    }//GEN-LAST:event_computingJButtonActionPerformed

    private void learningJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_learningJButtonActionPerformed
        dispose();
        LearningSupport DGUI = new LearningSupport();
        DGUI.setVisible(true);
    }//GEN-LAST:event_learningJButtonActionPerformed

    private void resourcesJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resourcesJButtonActionPerformed
        dispose();
        MathsButtonPage DGUI = new MathsButtonPage();
        DGUI.setVisible(true);
    }//GEN-LAST:event_resourcesJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MathsSupport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MathsSupport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MathsSupport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MathsSupport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MathsSupport().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MathsGUI;
    private javax.swing.JLayeredPane MathsSupportGUI;
    private javax.swing.JButton computingJButton;
    private javax.swing.JButton disabilityJButton;
    private javax.swing.JButton homeJButton;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JButton learningJButton;
    private javax.swing.JButton resourcesJButton;
    // End of variables declaration//GEN-END:variables
}
