/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package supportapp;

/*
 *  Tutorial4.java
 *  18/04/2013
 * @author Paul Cuffe 11378541
 * @reference https://moodle.ncirl.ie/course/view.php?id=878/ArraysOfObjectsTriggerApplication.java
 */

public class Tutorial4 extends javax.swing.JFrame {

    private String feedbackText;
    private Tutorial4 qArray[];
    //declare count variable to keep track of how many objects are in array
    private int count;
    
    public Tutorial4() {
        initComponents();
        feedbackText = new String();
       Tutorial4[] a = new Tutorial4[0];
        //initialise count to 0
        Tutorial4 a1;
        Tutorial4 a2;
        Tutorial4 a3;
        Tutorial4 a4;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        homeJButton = new javax.swing.JButton();
        feedbackTf = new javax.swing.JTextField();
        submitJButton = new javax.swing.JButton();
        tutorial4JLabel = new javax.swing.JLabel();
        tutorialTF = new javax.swing.JLabel();
        tutorial4JButton = new javax.swing.JButton();
        jInternalFrame1 = new javax.swing.JInternalFrame();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        homeJButton.setText("Home");
        homeJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeJButtonActionPerformed(evt);
            }
        });
        homeJButton.setBounds(140, 63, 90, 40);
        jLayeredPane1.add(homeJButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        feedbackTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feedbackTfActionPerformed(evt);
            }
        });
        feedbackTf.setBounds(10, 380, 300, 30);
        jLayeredPane1.add(feedbackTf, javax.swing.JLayeredPane.DEFAULT_LAYER);

        submitJButton.setText("Submit");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });
        submitJButton.setBounds(110, 423, 100, 30);
        jLayeredPane1.add(submitJButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        tutorial4JLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/supportapp/Tutorial4Video.png"))); // NOI18N
        tutorial4JLabel.setBounds(0, 160, 320, 160);
        jLayeredPane1.add(tutorial4JLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        tutorialTF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/supportapp/Computing Tutorial 4.jpg"))); // NOI18N
        tutorialTF.setBounds(0, 0, 320, 480);
        jLayeredPane1.add(tutorialTF, javax.swing.JLayeredPane.DEFAULT_LAYER);

        tutorial4JButton.setText("VIDEO");
        tutorial4JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tutorial4JButtonActionPerformed(evt);
            }
        });
        tutorial4JButton.setBounds(0, 160, 320, 160);
        jLayeredPane1.add(tutorial4JButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        jInternalFrame1.setBounds(60, 100, 22, 41);
        jLayeredPane1.add(jInternalFrame1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeJButtonActionPerformed
        dispose();
        HomeScreen DGUI = new HomeScreen();
        DGUI.setVisible(true);
    }//GEN-LAST:event_homeJButtonActionPerformed

    private void feedbackTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feedbackTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_feedbackTfActionPerformed

    private void tutorial4JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tutorial4JButtonActionPerformed
        try{
            String URL ="http://www.youtube.com/watch?v=3EE7E3bvfe8";
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(URL));
        }
        catch (Exception e) {
        }
    }//GEN-LAST:event_tutorial4JButtonActionPerformed

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
         // Get text from TextFields
        feedbackText = feedbackTf.getText();
        
        //create a new Question object
        
        
        //add contents of textfields to q
        
        
        //add q to array of Question objects
        
        //increase count to show that another object has been added to the array
        
        dispose();
        Tutorial4 DGUI = new Tutorial4();
        DGUI.setVisible(true);
    }//GEN-LAST:event_submitJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tutorial4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tutorial4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tutorial4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tutorial4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Tutorial4().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField feedbackTf;
    private javax.swing.JButton homeJButton;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JButton submitJButton;
    private javax.swing.JButton tutorial4JButton;
    private javax.swing.JLabel tutorial4JLabel;
    private javax.swing.JLabel tutorialTF;
    // End of variables declaration//GEN-END:variables
}
